### ISSUE TITLE
Importing OFXTree gives "'String' object has no attribute '__signature__'" on script execution

### ISSUE THREAD

**Issue by BenjaminPalko** [csingley/ofxtools#135]
Other modules being imported to the same module are `os`, `csv`, `PySide6.QtWidgets`, `PySide6.QtCore`, `PySide6.QtGui`

Removing the import immediately solves the execution error

Stack Trace:
```
Traceback (most recent call last):
  File "F:\Benja\Development\PycharmProjects\Budgeting\src\main.py", line 1, in <module>
    from src.ui.main_application import MainApplication
  File "F:\Benja\Development\PycharmProjects\Budgeting\src\ui\main_application.py", line 11, in <module>
    from src.ui.statements.statements_widget import StatementsWidget
  File "F:\Benja\Development\PycharmProjects\Budgeting\src\ui\statements\statements_widget.py", line 7, in <module>
    from ofxtools import OFXTree
  File "F:\Benja\Development\PycharmProjects\Budgeting\venv\lib\site-packages\ofxtools\__init__.py", line 3, in <module>
    from ofxtools.Client import OFXClient
  File "F:\Benja\Development\PycharmProjects\Budgeting\venv\lib\site-packages\ofxtools\Client.py", line 75, in <module>
    from ofxtools.header import make_header
  File "F:\Benja\Development\PycharmProjects\Budgeting\venv\lib\site-packages\ofxtools\header.py", line 88, in <module>
    class OFXHeaderV1(OFXHeaderBase):
  File "F:\Benja\Development\PycharmProjects\Budgeting\venv\lib\site-packages\ofxtools\header.py", line 101, in OFXHeaderV1
    oldfileuid = Types.String(36)
  File "F:\Benja\Development\PycharmProjects\Budgeting\venv\lib\site-packages\ofxtools\Types.py", line 137, in __init__
    bound = self.__signature__.bind(*args, **kwargs)
AttributeError: 'String' object has no attribute '__signature__'

Process finished with exit code 1
```

**Comment by csingley** [comment]
Glad you got it sorted out!
