### ISSUE TITLE
ofxget stmt with BECU returns HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by meonkeys** [csingley/ofxtools#189]
I'm trying to connect to BECU with ofxtools 0.9.5. I'm using Python 3.12.5.

I'm able to run `ofxget list`.

`$ ofxget stmt <server_nickname> -u <your_username> --all` with real values returns:

```
Password: 
Traceback (most recent call last):
  File "/usr/local/bin/ofxget", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/scripts/ofxget.py", line 1612, in main
    REQUEST_HANDLERS[args["request"]](args)
  File "/usr/local/lib/python3.12/site-packages/ofxtools/scripts/ofxget.py", line 723, in request_stmt
    with client.request_statements(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/Client.py", line 354, in request_statements
    RqCls2url = self._get_service_urls(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/Client.py", line 434, in _get_service_urls
    profile = self.request_profile(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/Client.py", line 506, in request_profile
    response = self._request_profile(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/Client.py", line 581, in _request_profile
    return self.download(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/Client.py", line 868, in download
    response = self.post_request(url, request, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ofxtools/Client.py", line 905, in post_request
    response = opener.open(req, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by meonkeys** [comment]
Ah, this is probably just another symptom of https://github.com/csingley/ofxtools/discussions/186

**Comment by csingley** [comment]
Linked to discussion #186 — FI-specific behavior. Not actionable without access to BECU. Please reopen if a root cause in ofxtools is identified.
