### ISSUE TITLE
parser.convert() fails for sample file

### ISSUE THREAD

**Issue by chbndrhnns** [csingley/ofxtools#27]
I am following the Usage Example:

```
from ofxtools.Parser import OFXTree
parser = OFXTree()
parser.parse('file') 
ofx = parser.convert()
```

gives me 

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jo/.virtualenvs/m2ynab/lib/python2.7/site-packages/ofxtools-0.5-py2.7.egg/ofxtools/models/ofx.py", line 51, in __repr__
    self.sonrs.fi.fid,
AttributeError: 'NoneType' object has no attribute 'fid'
```

[ofx.txt](https://github.com/csingley/ofxtools/files/1141842/ofx.txt)

**Comment by csingley** [comment]
Yup, SONRS isn't required to have an FI.
Try the fix I just pushed to master.

**Comment by chbndrhnns** [comment]
Works perfectly now in this regard!
