### ISSUE TITLE
ofxget hang downloading from Schwab brokerage

### ISSUE THREAD

**Issue by KnBrckr** [csingley/ofxtools#46]
Trying to get ofx file for my Schwab brokerage account and cant get ofxtools to work.

It's hanging when attempting to attach to Schwab. I found a thread that mentions a matching symptom and possible fix:  [http://www.ofxhome.com/ofxforum/viewtopic.php?id=47480](url)

The suggested fix in that case was to remove the 'User Agent' field from the request.

I do not know if this is the source of the problem. I have been able to get the OFX data via curl, see below for curl details.

My configuration for the account:
```
url: https://ofx.schwab.com/cgi_dev/ofx_server
org: ICS
fid: 5401
brokerid: SCHWAB.COM
investment: <account-number>
version: 102
appid: QWIN
appver: 2200
user: <user-name>
```

Here's the trace following ctrl-c:
Traceback (most recent call last):
```
  File "/usr/local/bin/ofxget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ofxtools/Client.py", line 456, in main
    do_stmt(args)
  File "/usr/local/lib/python2.7/site-packages/ofxtools/Client.py", line 312, in do_stmt
    dryrun=args.dryrun, **stmtrqs).read()
  File "/usr/local/lib/python2.7/site-packages/ofxtools/Client.py", line 149, in request_statements
    return self.download(ofx, dryrun=dryrun)
  File "/usr/local/lib/python2.7/site-packages/ofxtools/Client.py", line 228, in download
    response = requests.post(self.url, data=data, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
```

I have been able to download the OFX data using curl:

`curl -v -X POST --data-binary @ofx.request --header "Content-Type: application/x-ofx" --header "Accept:*/*, application/x-ofx" https://ofx.schwab.com/cgi_dev/ofx_server`

Contents of ofx.request (redacted):
```
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX><SIGNONMSGSRQV1><SONRQ><DTCLIENT>20180809075232.000<USERID>[username]<USERPASS>[password]<LANGUAGE>ENG<FI><ORG>SCHWAB.COM<FID>5104</FI><APPID>QWIN<APPVER>2200</SONRQ></SIGNONMSGSRQV1><INVSTMTMSGSRQV1><INVSTMTTRNRQ><TRNUID>20180809075232.000<CLTCOOKIE>1<INVSTMTRQ><INVACCTFROM><BROKERID>SCHWAB.COM<ACCTID>[account]</INVACCTFROM><INCTRAN><DTSTART>20180701<DTEND>20180731<INCLUDE>Y</INCTRAN><INCOO>Y<INCPOS><DTASOF>20180809075232.000<INCLUDE>Y</INCPOS><INCBAL>Y</INVSTMTRQ></INVSTMTTRNRQ></INVSTMTMSGSRQV1></OFX>
```

**Comment by csingley** [comment]
First off, trying updating `ofxtools`... preferably to git master, but current version on PyPI should be fine.  Your error message says `Client.py` calls out to `requests` on line 228, but it's not there now; you're missing some more recent code.

In the lines immediately preceding that call to `requests`, you should be able plainly to see where I set the POST headers to exactly the same as your curl args; I didn't set `user-agent`.

Another possible source of trouble is that some FIS are dicks about the APPID/APPVER elements inside SONRQ.  Was that `ofx.request` file you're using for `curl` generated by `ofxtools`?  What does `ofxtools.Client` output if you append the `--dryrun` argument?

**Comment by KnBrckr** [comment]
That change to headers did the trick!

Now to figure out how to download from chase credit card...

**Comment by csingley** [comment]
I'll commit a fix to the repository, thanks for reporting.

I _think_ JPM doesn't limit access to their OFX server for credit cards (unlike deposit products, where they want you pay a monthly fee unless you've got a premium account type)... but the URL I used to use for them is now returning HTTP 502.  jseutter probably has better info over at ofxhome.

一路順風

**Comment by KnBrckr** [comment]
Thank you for the help!!

I've been able to get gnucash configured to pull from Chase.  They have an extra step now required using Client UUID that must be approved to allow access.  After configuring a client uuid into GnuCash downloads are working.

See this thread for some discussion:  [http://www.ofxhome.com/ofxforum/viewtopic.php?id=47456](url)

**Comment by csingley** [comment]
Try passing the `--clientuid` argument to `ofxget` CLI.
