### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'verbose'

### ISSUE THREAD

**Issue by rvernica** [csingley/ofxtools#81]
```
> ofxget
Traceback (most recent call last):
  File "/home/foo/.local/bin/ofxget", line 8, in <module>
    sys.exit(main())
  File "/home/foo/.local/lib/python3.8/site-packages/ofxtools/scripts/ofxget.py", line 1489, in main
    log_level = LOG_LEVELS.get(args_.verbose, logging.DEBUG)
AttributeError: 'Namespace' object has no attribute 'verbose'
```
Version info:
```
> pip install --user --upgrade ofxtools
Collecting ofxtools
  Downloading ofxtools-0.8.20.tar.gz (104 kB)
...
> python
Python 3.8.2 (default, May  7 2020, 20:00:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ofxtools
>>> ofxtools.__version__
'0.8.20'
```

**Comment by csingley** [comment]
Sorry about that, I missed that (rather obvious) case!
