### ISSUE TITLE
USAA HTTP Error 400: Bad request on OFXClient example code. 

### ISSUE THREAD

**Issue by kwkaiser** [csingley/ofxtools#90]
When using the OFXClient docstring sample code with USAA, urllib returns a 400 bad request error. 

Here is a minimal use case: 

```python
from ofxtools.Client import OFXClient, StmtRq

client = OFXClient(
        url = "https://service2.usaa.com/ofx/OFXServlet",
        org = "USAA",
        fid = "24591",
        userid = "myuserid",
        bankid = "314074269"
        )

state = StmtRq(
        acctid  = "myacctid",
        accttype = "CHECKING"
        )

response = client.request_statements("mypassword", state)
```

Here is the error it yields:
```
Traceback (most recent call last):
  File "test2.py", line 16, in <module>
    response = client.request_statements("mypassword", state)
  File "/home/kwkaiser/Desktop/fintech/env/lib/python3.8/site-packages/ofxtools/Client.py", line 334, in request_statements
    return self.download(ofx, dryrun=dryrun, verify_ssl=verify_ssl, timeout=timeout)
  File "/home/kwkaiser/Desktop/fintech/env/lib/python3.8/site-packages/ofxtools/Client.py", line 590, in download
    response = urllib_request.urlopen(req, timeout=timeout, context=ssl_context)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by csingley** [comment]
`ofxget stmt usaa` works for me.  Did you read [this](https://ofxtools.readthedocs.io/en/latest/client.html#scanning-for-ofx-connection-formats)?

**Comment by csingley** [comment]
If the documented formats for USAA don't work, feel free to reopen the issue.
